export interface PricingRecord {
  id: string;
  partNumber: string;
  country: string;
  customerName: string;
  date: string; // ISO
  unitPrice: number;
  discount: number; // %
  currency: string;
  qty: number;
  contractType: 'Contract' | 'Spot';
  leadTimeDays: number;
}

export const PRICING_DB: PricingRecord[] = [
  // FP80C-CB1.3 — UK
  {
    id: 'H001',
    partNumber: 'FP80C-CB1.3',
    country: 'UK',
    customerName: 'PDAS Group Ltd',
    date: '2024-02-10',
    unitPrice: 1950,
    discount: 5,
    currency: 'GBP',
    qty: 1,
    contractType: 'Contract',
    leadTimeDays: 3,
  },
  {
    id: 'H002',
    partNumber: 'FP80C-CB1.3',
    country: 'UK',
    customerName: 'Thames Water',
    date: '2024-05-18',
    unitPrice: 1870,
    discount: 8,
    currency: 'GBP',
    qty: 2,
    contractType: 'Contract',
    leadTimeDays: 4,
  },
  {
    id: 'H003',
    partNumber: 'FP80C-CB1.3',
    country: 'UK',
    customerName: 'Anglian Water',
    date: '2024-08-22',
    unitPrice: 1920,
    discount: 6,
    currency: 'GBP',
    qty: 1,
    contractType: 'Spot',
    leadTimeDays: 5,
  },
  {
    id: 'H004',
    partNumber: 'FP80C-CB1.3',
    country: 'UK',
    customerName: 'PDAS Group Ltd',
    date: '2024-11-05',
    unitPrice: 1890,
    discount: 10,
    currency: 'GBP',
    qty: 3,
    contractType: 'Contract',
    leadTimeDays: 3,
  },
  {
    id: 'H005',
    partNumber: 'FP80C-CB1.3',
    country: 'UK',
    customerName: 'Severn Trent',
    date: '2025-01-14',
    unitPrice: 1830,
    discount: 7,
    currency: 'GBP',
    qty: 1,
    contractType: 'Spot',
    leadTimeDays: 6,
  },
  {
    id: 'H006',
    partNumber: 'FP80C-CB1.3',
    country: 'UK',
    customerName: 'Clean Water Group',
    date: '2025-04-09',
    unitPrice: 1860,
    discount: 8,
    currency: 'GBP',
    qty: 2,
    contractType: 'Contract',
    leadTimeDays: 4,
  },
  {
    id: 'H007',
    partNumber: 'FP80C-CB1.3',
    country: 'UK',
    customerName: 'Yorkshire Water',
    date: '2025-07-21',
    unitPrice: 1845,
    discount: 9,
    currency: 'GBP',
    qty: 1,
    contractType: 'Contract',
    leadTimeDays: 3,
  },
  {
    id: 'H008',
    partNumber: 'FP80C-CB1.3',
    country: 'UK',
    customerName: 'PDAS Group Ltd',
    date: '2025-10-30',
    unitPrice: 1820,
    discount: 10,
    currency: 'GBP',
    qty: 2,
    contractType: 'Contract',
    leadTimeDays: 3,
  },
  // FP80C-CB1.3 — Germany
  {
    id: 'H009',
    partNumber: 'FP80C-CB1.3',
    country: 'Germany',
    customerName: 'Berliner Wasserbetriebe',
    date: '2024-03-15',
    unitPrice: 2100,
    discount: 5,
    currency: 'EUR',
    qty: 1,
    contractType: 'Spot',
    leadTimeDays: 7,
  },
  {
    id: 'H010',
    partNumber: 'FP80C-CB1.3',
    country: 'Germany',
    customerName: 'Hamburger Wasserwerke',
    date: '2025-02-20',
    unitPrice: 2050,
    discount: 6,
    currency: 'EUR',
    qty: 2,
    contractType: 'Contract',
    leadTimeDays: 5,
  },

  // GS-1049 — Brazil
  {
    id: 'H011',
    partNumber: 'GS-1049',
    country: 'Brazil',
    customerName: 'Petro-Brasil SA',
    date: '2024-01-08',
    unitPrice: 28,
    discount: 0,
    currency: 'BRL',
    qty: 12,
    contractType: 'Spot',
    leadTimeDays: 7,
  },
  {
    id: 'H012',
    partNumber: 'GS-1049',
    country: 'Brazil',
    customerName: 'Petro-Brasil SA',
    date: '2024-04-22',
    unitPrice: 30,
    discount: 5,
    currency: 'BRL',
    qty: 24,
    contractType: 'Contract',
    leadTimeDays: 5,
  },
  {
    id: 'H013',
    partNumber: 'GS-1049',
    country: 'Brazil',
    customerName: 'Sabesp',
    date: '2024-07-11',
    unitPrice: 29,
    discount: 3,
    currency: 'BRL',
    qty: 12,
    contractType: 'Spot',
    leadTimeDays: 8,
  },
  {
    id: 'H014',
    partNumber: 'GS-1049',
    country: 'Brazil',
    customerName: 'Petro-Brasil SA',
    date: '2024-10-19',
    unitPrice: 31,
    discount: 5,
    currency: 'BRL',
    qty: 36,
    contractType: 'Contract',
    leadTimeDays: 5,
  },
  {
    id: 'H015',
    partNumber: 'GS-1049',
    country: 'Brazil',
    customerName: 'Sabesp',
    date: '2025-03-05',
    unitPrice: 30,
    discount: 4,
    currency: 'BRL',
    qty: 12,
    contractType: 'Spot',
    leadTimeDays: 7,
  },
  {
    id: 'H016',
    partNumber: 'GS-1049',
    country: 'Brazil',
    customerName: 'Petro-Brasil SA',
    date: '2025-06-14',
    unitPrice: 32,
    discount: 5,
    currency: 'BRL',
    qty: 48,
    contractType: 'Contract',
    leadTimeDays: 4,
  },
  // GS-1049 — UAE
  {
    id: 'H017',
    partNumber: 'GS-1049',
    country: 'UAE',
    customerName: 'DEWA',
    date: '2024-06-01',
    unitPrice: 35,
    discount: 0,
    currency: 'USD',
    qty: 10,
    contractType: 'Spot',
    leadTimeDays: 10,
  },
  {
    id: 'H018',
    partNumber: 'GS-1049',
    country: 'UAE',
    customerName: 'ADWEA',
    date: '2025-01-17',
    unitPrice: 33,
    discount: 3,
    currency: 'USD',
    qty: 20,
    contractType: 'Contract',
    leadTimeDays: 8,
  },

  // FP100G-CB1.5 — UK
  {
    id: 'H019',
    partNumber: 'FP100G-CB1.5',
    country: 'UK',
    customerName: 'Clean Water Group',
    date: '2024-02-28',
    unitPrice: 2200,
    discount: 5,
    currency: 'GBP',
    qty: 1,
    contractType: 'Contract',
    leadTimeDays: 4,
  },
  {
    id: 'H020',
    partNumber: 'FP100G-CB1.5',
    country: 'UK',
    customerName: 'Northumbrian Water',
    date: '2024-06-10',
    unitPrice: 2150,
    discount: 7,
    currency: 'GBP',
    qty: 2,
    contractType: 'Contract',
    leadTimeDays: 4,
  },
  {
    id: 'H021',
    partNumber: 'FP100G-CB1.5',
    country: 'UK',
    customerName: 'Clean Water Group',
    date: '2024-09-25',
    unitPrice: 2180,
    discount: 6,
    currency: 'GBP',
    qty: 1,
    contractType: 'Contract',
    leadTimeDays: 5,
  },
  {
    id: 'H022',
    partNumber: 'FP100G-CB1.5',
    country: 'UK',
    customerName: 'United Utilities',
    date: '2025-01-30',
    unitPrice: 2120,
    discount: 8,
    currency: 'GBP',
    qty: 3,
    contractType: 'Contract',
    leadTimeDays: 4,
  },
  {
    id: 'H023',
    partNumber: 'FP100G-CB1.5',
    country: 'UK',
    customerName: 'Clean Water Group',
    date: '2025-05-12',
    unitPrice: 2100,
    discount: 8,
    currency: 'GBP',
    qty: 2,
    contractType: 'Contract',
    leadTimeDays: 4,
  },

  // 31055123 M — USA
  {
    id: 'H024',
    partNumber: '31055123 M',
    country: 'USA',
    customerName: 'Detroit Municipal Water',
    date: '2023-11-14',
    unitPrice: 3600,
    discount: 5,
    currency: 'USD',
    qty: 1,
    contractType: 'Contract',
    leadTimeDays: 14,
  },
  {
    id: 'H025',
    partNumber: '31055123 M',
    country: 'USA',
    customerName: 'Chicago Water Dept',
    date: '2024-03-08',
    unitPrice: 3750,
    discount: 3,
    currency: 'USD',
    qty: 1,
    contractType: 'Spot',
    leadTimeDays: 16,
  },
  {
    id: 'H026',
    partNumber: '31055123 M',
    country: 'USA',
    customerName: 'Detroit Municipal Water',
    date: '2024-07-22',
    unitPrice: 3680,
    discount: 5,
    currency: 'USD',
    qty: 1,
    contractType: 'Contract',
    leadTimeDays: 12,
  },
  {
    id: 'H027',
    partNumber: '31055123 M',
    country: 'USA',
    customerName: 'LA Sanitation',
    date: '2024-11-30',
    unitPrice: 3900,
    discount: 2,
    currency: 'USD',
    qty: 2,
    contractType: 'Spot',
    leadTimeDays: 18,
  },
  {
    id: 'H028',
    partNumber: '31055123 M',
    country: 'USA',
    customerName: 'Detroit Municipal Water',
    date: '2025-04-15',
    unitPrice: 3720,
    discount: 5,
    currency: 'USD',
    qty: 1,
    contractType: 'Contract',
    leadTimeDays: 12,
  },
  // 31055123 M — Germany
  {
    id: 'H029',
    partNumber: '31055123 M',
    country: 'Germany',
    customerName: 'Stadtwerke München',
    date: '2024-05-20',
    unitPrice: 4100,
    discount: 4,
    currency: 'EUR',
    qty: 1,
    contractType: 'Spot',
    leadTimeDays: 10,
  },
  {
    id: 'H030',
    partNumber: '31055123 M',
    country: 'Germany',
    customerName: 'RWW Rheinisch',
    date: '2025-02-11',
    unitPrice: 3980,
    discount: 5,
    currency: 'EUR',
    qty: 2,
    contractType: 'Contract',
    leadTimeDays: 9,
  },

  // RP008 — India
  {
    id: 'H031',
    partNumber: 'RP008',
    country: 'India',
    customerName: 'ONGC',
    date: '2023-09-05',
    unitPrice: 145000,
    discount: 0,
    currency: 'INR',
    qty: 1,
    contractType: 'Spot',
    leadTimeDays: 60,
  },
  {
    id: 'H032',
    partNumber: 'RP008',
    country: 'India',
    customerName: 'IOCL',
    date: '2024-01-20',
    unitPrice: 162000,
    discount: 2,
    currency: 'INR',
    qty: 2,
    contractType: 'Contract',
    leadTimeDays: 45,
  },
  {
    id: 'H033',
    partNumber: 'RP008',
    country: 'India',
    customerName: 'thyssenkrupp Uhde India',
    date: '2024-06-14',
    unitPrice: 175000,
    discount: 3,
    currency: 'INR',
    qty: 1,
    contractType: 'Spot',
    leadTimeDays: 50,
  },
  {
    id: 'H034',
    partNumber: 'RP008',
    country: 'India',
    customerName: 'HPCL',
    date: '2024-10-08',
    unitPrice: 180000,
    discount: 2,
    currency: 'INR',
    qty: 3,
    contractType: 'Contract',
    leadTimeDays: 42,
  },
  {
    id: 'H035',
    partNumber: 'RP008',
    country: 'India',
    customerName: 'thyssenkrupp Uhde India',
    date: '2025-03-22',
    unitPrice: 183000,
    discount: 3,
    currency: 'INR',
    qty: 1,
    contractType: 'Contract',
    leadTimeDays: 45,
  },
];

export interface TechRecord {
  partNumber: string;
  description: string;
  pumpModel: string;
  material: string;
  compatibleSerials: string[];
  stockLevel: number;
  stockLocation: string;
  lastDocRevision: string;
  isoCompliance: string;
  avgServiceLifeYears: number;
  bundledWith: string[];
  bundleFrequencyPct: number;
  knownIssues: string | null;
  sapLeadTimeStd: number;
  sapLeadTimeExpress: number;
}

export const TECH_DB: Record<string, TechRecord> = {
  'FP80C-CB1.3': {
    partNumber: 'FP80C-CB1.3',
    description: 'Hydraulic Refurbishment Kit — Impeller & Wear Ring Assembly',
    pumpModel: 'XFP-PE1-80C-CB1.3',
    material: 'Cast Iron / Stainless Steel Shaft',
    compatibleSerials: ['301009200', '301009201', '301009202'],
    stockLevel: 8,
    stockLocation: 'Crawley UK Warehouse',
    lastDocRevision: 'Rev.7 — March 2025',
    isoCompliance: 'ISO 9001:2015, EN 12050',
    avgServiceLifeYears: 4,
    bundledWith: ['O-Ring Kit 11120520', 'Cap Screw Set 11210246'],
    bundleFrequencyPct: 78,
    knownIssues: null,
    sapLeadTimeStd: 3,
    sapLeadTimeExpress: 1,
  },
  'GS-1049': {
    partNumber: 'GS-1049',
    description: 'Industrial Gasket Seal — NBR Compound, 215.49×3.53mm',
    pumpModel: 'Universal (XFP / ABS Series)',
    material: 'NBR Rubber Compound',
    compatibleSerials: ['SN-481920', 'SN-481921', 'SN-481922'],
    stockLevel: 45,
    stockLocation: 'Pune Hub Warehouse',
    lastDocRevision: 'Rev.4 — Jan 2025',
    isoCompliance: 'ISO 3601-1, DIN 3771',
    avgServiceLifeYears: 2,
    bundledWith: ['Lock Washer 11490027'],
    bundleFrequencyPct: 42,
    knownIssues: null,
    sapLeadTimeStd: 5,
    sapLeadTimeExpress: 2,
  },
  'FP100G-CB1.5': {
    partNumber: 'FP100G-CB1.5',
    description: 'Hydraulic Wear Kit — Impeller Seal & Casing Liner',
    pumpModel: 'XFP 100G-CB1.5',
    material: 'Duplex Stainless Steel',
    compatibleSerials: ['301008544', '301008545'],
    stockLevel: 4,
    stockLocation: 'Leeds Local Hub',
    lastDocRevision: 'Rev.5 — Feb 2025',
    isoCompliance: 'ISO 9001:2015, BS EN 809',
    avgServiceLifeYears: 5,
    bundledWith: ['Seal Ring Set', 'Wear Plate Assembly'],
    bundleFrequencyPct: 65,
    knownIssues: 'Minor cavitation risk at >85% duty point — verify operating curve.',
    sapLeadTimeStd: 4,
    sapLeadTimeExpress: 2,
  },
  '31055123 M': {
    partNumber: '31055123 M',
    description: 'Heavy-Duty Impeller & Shaft Assembly — Custom Machined',
    pumpModel: 'Municipal Wastewater Series',
    material: 'High-Chrome Alloy / Hardened Steel Shaft',
    compatibleSerials: ['301009201'],
    stockLevel: 0,
    stockLocation: 'Made-to-Order (Winterthur Plant)',
    lastDocRevision: 'Rev.3 — Nov 2024',
    isoCompliance: 'ISO 9001:2015, ASME B73.1',
    avgServiceLifeYears: 8,
    bundledWith: ['Dynamic Balancing Test Report', 'NDT Certificate'],
    bundleFrequencyPct: 100,
    knownIssues:
      'Requires custom impeller diameter sizing — confirm operating RPM and fluid density before order.',
    sapLeadTimeStd: 14,
    sapLeadTimeExpress: 7,
  },
  RP008: {
    partNumber: 'RP008',
    description: 'Non-API Centrifugal Slurry Pump — EPC Design & Supply',
    pumpModel: 'Slurry Series (Custom EPC)',
    material: 'High-Chrome White Iron / Rubber-Lined Casing',
    compatibleSerials: ['O4QO-12659'],
    stockLevel: 0,
    stockLocation: 'Engineering-to-Order (Pune Design Centre)',
    lastDocRevision: 'Rev.1 — May 2025',
    isoCompliance: 'ISO 9001:2015, API 610 (adapted), IS 5120',
    avgServiceLifeYears: 12,
    bundledWith: ['Hydraulic Simulation Report', 'Deviation Sheet', 'Material Certificates'],
    bundleFrequencyPct: 100,
    knownIssues:
      'Solid particle concentration and fluid density must be confirmed before hydraulic selection.',
    sapLeadTimeStd: 45,
    sapLeadTimeExpress: 30,
  },
};

export function getPricingHistory(partNumber: string, country: string): PricingRecord[] {
  return PRICING_DB.filter(r => r.partNumber === partNumber && r.country === country).sort(
    (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
  );
}

export function getAvgPrice(records: PricingRecord[]): number {
  if (!records.length) return 0;
  return records.reduce((s, r) => s + r.unitPrice, 0) / records.length;
}

export function getAvgDiscount(records: PricingRecord[]): number {
  if (!records.length) return 0;
  return records.reduce((s, r) => s + r.discount, 0) / records.length;
}

export function getPriceTrend(records: PricingRecord[]): 'up' | 'down' | 'stable' {
  if (records.length < 2) return 'stable';
  const first = records[0].unitPrice;
  const last = records[records.length - 1].unitPrice;
  const delta = ((last - first) / first) * 100;
  if (delta > 3) return 'up';
  if (delta < -3) return 'down';
  return 'stable';
}
